spring.application.name=sistema-gate
server.port=${PORT:8080}

spring.main.web-application-type=reactive

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.client=DEBUG

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=false
spring.cloud.gateway.globalcors.cors-configurations[/**].allowed-origins=
spring.cloud.gateway.globalcors.cors-configurations[/**].allowed-methods=
spring.cloud.gateway.globalcors.cors-configurations[/**].allowed-headers=
