spring.application.name=sistema-gate
server.port=${PORT:8080}
spring.main.web-application-type=reactive
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.client=DEBUG


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

spring.cloud.gateway.mvc.routes[0].id=api-usuarios
spring.cloud.gateway.mvc.routes[0].uri=https://api-usuarios-nrht.onrender.com
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/usuarios/**

spring.cloud.gateway.mvc.routes[1].id=api-perfiles
spring.cloud.gateway.mvc.routes[1].uri=https://api-usuarios-nrht.onrender.com
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/v1/perfiles/**

spring.cloud.gateway.mvc.routes[2].id=api-academica
spring.cloud.gateway.mvc.routes[2].uri=https://api-academica-w9eo.onrender.com
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/cursos/**,/api/asignaturas/**,/api/evaluaciones/**,/api/notas/**

spring.cloud.gateway.mvc.routes[3].id=api-asistencia
spring.cloud.gateway.mvc.routes[3].uri=https://api-asistencia-node.onrender.com
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/v1/asistencias/**,/api/v1/anotaciones/**,/api/v1/justificaciones/**

spring.cloud.gateway.mvc.routes[4].id=api-comunicacion
spring.cloud.gateway.mvc.routes[4].uri=https://api-comunicacion.onrender.com
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/mensajes/**,/api/conversaciones/**,/api/notificaciones/**,/api/grupos/**,/api/adjuntos/**,/api/plantillas/**,/api/mensajes-grupales/**,/api/configuracion-notificaciones/**,/api/comunicacion/**
