spring.application.name=sistema-gate
server.port=${PORT:8080}
spring.mvc.async.request-timeout=30000

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

spring.cloud.gateway.mvc.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.mvc.globalcors.cors-configurations.[/**].allowed-methods=*
spring.cloud.gateway.mvc.globalcors.cors-configurations.[/**].allowed-headers=*

spring.cloud.gateway.mvc.routes[0].id=api-usuarios
spring.cloud.gateway.mvc.routes[0].uri=https://api-usuarios-nrht.onrender.com
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/v1/usuarios/**

spring.cloud.gateway.mvc.routes[1].id=api-academica
spring.cloud.gateway.mvc.routes[1].uri=https://api-academica-w9eo.onrender.com
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/cursos/**,/api/asignaturas/**,/api/evaluaciones/**,/api/notas/**

spring.cloud.gateway.mvc.routes[2].id=api-asistencia
spring.cloud.gateway.mvc.routes[2].uri=https://api-asistencia-bo6s.onrender.com
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/v1/asistencias/**

spring.cloud.gateway.mvc.routes[3].id=api-comunicacion
spring.cloud.gateway.mvc.routes[3].uri=https://api-comunicacion.onrender.com
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/mensajes/**,/api/conversaciones/**,/api/notificaciones/**,/api/grupos/**,/api/adjuntos/**,/api/plantillas/**,/api/mensajes-grupales/**,/api/comunicacion/**
